name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/robosys2022_ros2/
          cd /root/ros2_ws
          sudo apt-get install python3-rosdep
          bash -xv ./src/robosys2022_ros2/test/test.bash /root